### ISSUE TITLE
How to get and set the .data attributes?

### ISSUE THREAD

**Issue by georgeu2000** [opal/opal-jquery#50]
For example,

`Element.find( "#element" ).data( "foo", 52 );` ...?

http://api.jquery.com/data/#data1

**Comment by AlexWayfer** [comment]
Can I get and print values of all `data` attributes?

```ruby
p element.data # doesn't work
# jQuery.Deferred exception: obj.$inspect is not a function TypeError: obj.$inspect is not a function
puts element.data # doesn't work
# jQuery.Deferred exception: object.$respond_to? is not a function TypeError: object.$respond_to? is not a function
element.data.each { |data| p data } # or puts; doesn't work
# jQuery.Deferred exception: Cannot set property '$$p' of undefined TypeError: Cannot set property '$$p' of undefined
```

Thanks.

**Comment by elia** [comment]
@AlexWayfer `Element#data` [just forwards the arguments](https://github.com/opal/opal-jquery/blob/master/lib/opal/jquery/element.rb#L518-L523) to the [original jQuery's `data()` function](http://api.jquery.com/data/) so the setter (`el.data('foo', 123)` and getter (`el.data('foo') // => 123`) should work fine. Calling it without arguments could be effectively bugged as it's probably returning the native object instead of a hash.

I'll reopen this as it probably **needs some more testing and better documentation**. 

This is btw a _good first patch™_ if anyone's interested in contributing 🙂 (HINT HINT!)
